stages:
  - test

variables:
  NODE_ENV: test
  PLAYWRIGHT_BROWSERS_PATH: 0

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

playwright_tests:
  stage: test
  image: mcr.microsoft.com/playwright:v1.47.2-jammy
  before_script:
    - npm ci
    - npx playwright install --with-deps
  script:
    # Запуск тестів з HTML та Allure репортерами
    - npx playwright test --reporter=line,allure-playwright,html
    # Генерація HTML Allure репорту
    - npx allure generate ./allure-results -o ./allure-report
    - ls -la ./allure-report
    # Вивід посилання на репорт у логах GitLab
    - echo "Allure report is available here: ${CI_JOB_URL}/artifacts/file/allure-report/index.html"
  artifacts:
    when: always
    paths:
      - playwright-report/ # HTML Playwright звіт
      - allure-results/ # сирі результати Allure
      - allure-report/ # HTML Allure
    expire_in: 30 days

playwright_docker:
  stage: test
  image: docker:24
  services:
    - docker:dind
  before_script:
    - docker info
  script:
    - docker build -t playwright-tests .
    - docker run --rm -v $PWD:/app playwright-tests
  artifacts:
    when: always
    paths:
      - playwright-report/
      - allure-results/
      - allure-report/
    expire_in: 30 days
